name: Cl

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract ngrok
      run: Expand-Archive ngrok.zip -DestinationPath ngrok

    - name: Authenticate ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Set Local User Password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Create ngrok Tunnel
      run: |
        $ngrokPath = ".\ngrok\ngrok.exe"
        $port = 3389

        # Function to start ngrok
        function Start-Ngrok {
            Start-Process -NoNewWindow -FilePath $ngrokPath -ArgumentList "tcp $port"
            Write-Host "ngrok tunnel started on port $port."
        }

        # Start ngrok
        Start-Ngrok

        # Schedule the task to restart ngrok every hour
        $action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-Command `"$ngrokPath tcp $port`""
        $trigger = New-ScheduledTaskTrigger -At (Get-Date).AddHours(1) -Once
        Register-ScheduledTask -Action $action -Trigger $trigger -TaskName "RestartNgrok" -User "SYSTEM" -RunLevel Highest
